var projects = { // {{{
    'webifyme': 'Webify Me (Desktop)',
    'spark': 'Spark (Mobile)',
    'dstudio': 'MDN Demo Studio',
    'webowonder': 'Web O\'Wonder (Demo Microsite)',
    'markup': 'Mark Up (Desktop)',
    'tparty': 'Twitter Party (Desktop)',
    'joinmozilla': 'New \'Join Mozilla\' page on mozilla.org',
    'syncacc': 'New Services account page',
    'fbbadges': 'Facebook Badges',
    'glow': 'Global Map a.k.a. Glow - the new download stats page',
    'fbwebhero': 'Facebook Web Hero',
    'sparkeol': 'Spark EOL (End of Life)',
    'affiliates': 'Affiliates program website',
    'mozillians': 'Mozillians Directory',
    'firefox': 'Firefox localization',
    'thunderbird': 'Thunderbird localization',
    'calendar' : 'Calendar project(Lightning)',
} // }}}
